version: '3.9'  

services:
  db:
    image: postgres:15-alpine
    container_name: grafica_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: grafica_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: grafica_db
    restart: unless-stopped

  api:
    container_name: grafica-backend
    build: ./api-grafica
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    
    volumes:
      - media_volume:/app/media
      - api_static:/app/staticfiles  
    environment:
      DB_HOST: db
      DB_NAME: grafica_db
      DB_USER: grafica_user
      DB_PASSWORD: ${POSTGRES_PASSWORD} 
      DJANGO_SECRET_KEY: 'django-insecure-c5##wt(b&3!po^z*ya0f-y=c#!)2tm$wcyamu3e+*f7f9+9(p!' 
      DEBUG: 'False'
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: grafica-frontend
    build: ./frontend-grafica
    
    environment:
      NODE_ENV: production
      
      NEXT_PUBLIC_API_URL: http://92.112.176.145/api
      NEXT_PUBLIC_BACKEND_URL: http://92.112.176.145
      
      
      INTERNAL_API_URL: http://api:8000/api
      INTERNAL_BACKEND_URL: http://api:8000
    depends_on:
      - api
    restart: unless-stopped
      
  scheduler:
    container_name: grafica-scheduler
    build: ./api-grafica
    depends_on:
      - api
      - db
    environment:
      DB_HOST: db
      DB_NAME: grafica_db
      DB_USER: grafica_user
      DB_PASSWORD: ${POSTGRES_PASSWORD} 
      DJANGO_SECRET_KEY: 'django-insecure-c5##wt(b&3!po^z*ya0f-y=c#!)2tm$wcyamu3e+*f7f9+9(p!'
      DEBUG: 'False'
    command: >
      sh -c 'echo "Iniciando scheduler..."; 
             while true; do 
               python manage.py gerar_notificacoes;
               sleep 600;
             done'
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    container_name: grafica-proxy
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_volume:/app/media:ro
      - api_static:/app/staticfiles:ro          
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:   
  media_volume:
  api_static: 
